app/ts/components/Configure.tsx

Fixes bug where inputs for signing accounts would be cleared during validation check

Input bug fix

---

app/css/index.css
app/ts/components/App.tsx
app/ts/components/Submit.tsx

Displays human readable status of bundle submission attempts instead of stringified statuses of outcome enums.

Show when bundle attempts are mined, missed or pending

---

app/css/index.css
app/ts/components/App.tsx
app/ts/components/Configure.tsx
app/ts/components/Import.tsx
app/ts/components/NetworkDetails.tsx
app/ts/components/Submit.tsx
app/ts/components/Transactions.tsx

Fixes Error where you couldn't add signing keys to the inputs
Displays clearer details of the imported transactions
- shows calldata if contract not verified and shows parsed call when it is
- Shows transaction index and revert message when simulations revert when trying to simulate on the submit test
Users Etherscan API for fetching ABIs but we can change this in future

Human readable transactions

---

.prettierrc.json
app/css/index.css
app/ts/components/App.tsx
app/ts/components/Configure.tsx
app/ts/components/Navbar.tsx
app/ts/components/Settings.tsx
app/ts/components/Submit.tsx
app/ts/components/Transactions.tsx
app/ts/constants.ts
app/ts/library/bundleUtils.ts
app/ts/library/flashbots-ethers-provider.ts

Fixes #27 With modal popup to configure relay RPC, priority fee and how many blocks in future to target inclusion
fixes #4 Correct relay RPC is used, before this I found a bug where it would only use goerli relay even when mainnet selected.

Add Settings Modal

---

app/ts/components/App.tsx
app/ts/components/Import.tsx
app/ts/components/Navbar.tsx
app/ts/components/Transactions.tsx
app/ts/library/bundleUtils.ts
app/ts/stores.ts

Fetch funding wallet nonce, update tx list and simulation/submit to work with async function.
Also moved signals defined and u[dated in App.tsx to separate file.
Fixes #32

Fetch funding wallet nonce

---

app/css/index.css
app/ts/components/Configure.tsx
app/ts/components/Settings.tsx
app/ts/components/Submit.tsx
app/ts/components/Transactions.tsx
app/ts/library/asyncState.ts
app/ts/library/bundleUtils.ts
app/ts/library/provider.ts

Cleanup state, fix state sync and update issues

---

app/css/index.css
app/ts/components/App.tsx
app/ts/components/Import.tsx
app/ts/components/ImportModal.tsx
app/ts/components/Transactions.tsx
app/ts/library/bundleUtils.ts
app/ts/library/provider.ts
app/ts/library/utils.ts
app/ts/stores.ts
app/ts/types/bouquetTypes.ts
app/ts/types/interceptorTypes.ts

* Component style consistent with new style
* Shows correct input values needed from funding transactions (Fixes #41 )
* Simplified flow to check and display ABI decoded transactions, partially fixes problems with #50, remaining issue with this is on the Configure component
* Shows warning box if Interceptor has different simulation than the current transaction list in Bouquet. Fixes #49

Transactions and import diff

---

app/css/index.css
app/ts/components/App.tsx
app/ts/components/Button.tsx
app/ts/components/Configure.tsx
app/ts/components/Footer.tsx
app/ts/components/Import.tsx
app/ts/components/ImportModal.tsx
app/ts/components/Navbar.tsx
app/ts/components/Settings.tsx
app/ts/components/Submit.tsx
app/ts/components/Transactions.tsx
app/ts/components/Warns.tsx
app/ts/library/bundleUtils.ts
app/ts/library/provider.ts
app/ts/library/utils.ts
app/ts/stores.ts
app/ts/types/bouquetTypes.ts
app/ts/types/interceptorTypes.ts

- Fix Some edgecases where warnings are not hidden when resolved
- Changed Styling

Error handling clean, inputs for import better, new style

---

app/ts/components/Transactions.tsx
app/ts/components/Warns.tsx

Add click to import button on warning card about transaction stack diff

---

app/ts/components/Button.tsx
app/ts/components/Settings.tsx

- Only update settings on save click, instead of on edit now
- Show if input is invalid with red outline + disabled save button
- Button now shows disabled style on all variants

Settings Modal inputs now in sync with state 

---

app/ts/components/Transactions.tsx

Show correct value on tx list entries, seperate fee and value

---

app/ts/constants.ts

Current build is broken due to a type issue.
https://github.com/DarkFlorist/bouquet/actions/runs/6182238779/job/16781591768

Restore types, fix build

---

README.md
app/ts/components/Import.tsx

Fixes #68 
You can test these 2 scenarios, with make me rich enabled and then importing them into Bouquet.
**Scenario 1:**
Transaction with ETH sent back in internal transaction
```ts
// contract that sends back 50% of ETH to msg.sender and 50% to address(0) in constructor
ethereum.request({ method: "eth_sendTransaction", params: [{ to: null, data: "60806040525f341115610102575f60023461001a919061013d565b90505f3373ffffffffffffffffffffffffffffffffffffffff16826040516100419061019a565b5f6040518083038185875af1925050503d805f811461007b576040519150601f19603f3d011682016040523d82523d5f602084013e610080565b606091505b505090505f8073ffffffffffffffffffffffffffffffffffffffff16476040516100a99061019a565b5f6040518083038185875af1925050503d805f81146100e3576040519150601f19603f3d011682016040523d82523d5f602084013e61 …
```

Input value actual minimum

---

.github/workflows/ipfs-deploy.yml
Dockerfile

Added the IPFS workflow build which requires #77 
Resolves #76

Add IPFS docker build and workflow

---

.github/workflows/ipfs-deploy.yml
Dockerfile

Images are very minimal here and seem to all be working fine in bouquet
Resolves #76

Deploy app on IPFS

---

.github/workflows/ipfs-deploy.yml

Changed wrong branch reference from `master` to `main`

Change reference branch to main

---

app/ts/components/Navbar.tsx

fix https://github.com/DarkFlorist/bouquet/issues/92

add connect button to page if its not already being displayed

---

app/css/index.css
app/ts/components/Settings.tsx
package.json
twcss/package.json
twcss/tailwind.globals.css

Moved the styles to tailwind generator so that it doesn't get lost when the script is ran

Fix tailwind overwriting styles

---

app/ts/library/flashbots.ts

the field is `txs` not `transactions`: https://docs.flashbots.net/flashbots-auction/advanced/rpc-endpoint

flashbots wants variable name `txs` and not `transactions`

---

app/ts/components/Settings.tsx

add keys for inputs. Made text more rpc's more clear

---

app/ts/components/Settings.tsx
app/ts/components/Submit.tsx
app/ts/components/Transactions.tsx
app/ts/library/bundleUtils.ts
app/ts/library/flashbots.ts

- add 60 sec timeout to simulation
- reduce simulation stack query spamming to interceptor
- show simulation rpc being used at bottom
- fix typo
- some refactoring

add timeout (60 secs), reduce get simulation stack spamming to inteceptor, add more information to user

---

app/ts/components/Submit.tsx

firstRevert.error is sometimes object with code and error

use stringify instead of string
